theme: jekyll-theme-minimal

# Site-wide configuration
title: Asynchronous Many-Task systems for Exascale 2025
logo: /assets/logo.png
baseurl: ""
url: "https://amte-workshop.github.io"
conf_city: Dresden, Germany
acronym: AMTE 2025
workshop_date: August 25-29, 2025
current_year: 2025
